# example netlify.toml
[build]
  command = "hugo"
  functions = "netlify/functions"
  publish = "public"

  [build.environment]
    HUGO_VERSION = "0.101.0"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["./data/*.json", "data/*", "**.json", "netlify/functions/sample-data.json"]

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    enable = false

  [plugins.inputs.postBuild]
    enable = true