# example netlify.toml
[build]
  command = "hugo"
  publish = "public"

  [build.environment]
    HUGO_VERSION = "0.101.0"

[functions]
  node_bundler = "esbuild"
  included_files = ["./netlify/functions/a-nodejs-function/data/**"]

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    enable = false

  [plugins.inputs.postBuild]
    enable = true
